{% set name = "pyequib" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyequib-{{ version }}.tar.gz
  sha256: 187dd4d4c1183edbd2cc40954fb6e71fa9d187d937f400f0fa29335cc5237b2f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - numpy >=1.17
    - scipy >=1.2
    - atomneb >=0.3
  run:
    - python >=3.8
    - numpy >=1.17
    - scipy >=1.2
    - atomneb >=0.3
    
test:
  imports:
    - pyequib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/equib/pyEQUIB
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: 'pyEQUIB: Python Package for Plasma Diagnostics and Abundance Analysis'
  dev_url: https://github.com/equib/pyEQUIB
  doc_url: https://pypi.python.org/pypi/pyequib

extra:
  recipe-maintainers:
    - danehkar
